language: generic
sudo: required

services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - COLLECT_ERROR= 1

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build  --build-arg MYSQL_ROOT_PASSWORD=password -t razear/mega-electric-mysql-dev:latest -t razear/mega-electric-mysql-dev:$SHA -f Dockerfile.dev .
  - docker push razear/mega-electric-mysql-dev:latest
  - docker push razear/mega-electric-mysql-dev:$SHA

before_deploy:
  - docker build  -t razear/mega-electric-mysql:latest -t razear/mega-electric-mysql:$SHA -f Dockerfile .
  - docker push razear/mega-electric-mysql:latest
  - docker push razear/mega-electric-mysql:$SHA
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main