kind: InternalService
name: mega-electric-mysql
spec:
  image: mysql:latest
#  image_pull_policy: IfNotPresent
#  replicas: 1
  env:
    - MYSQL_ROOT_PASSWORD: the-secret-way-to-doing-stuff
    - MYSQL_DATABASE: inventory
#    - name: VERSION
#      value: v1
  port_mapping:
    - port: 3306
      target_port: 3306
      # default protocol is TCP
  resources:
    memory: 500Mi
  volume_mounts:
    - mount_path: /var/lib/mysql
      sub_path: mysql
      volume_name: vol1
